import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const json=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const r=json('docs/operations/under80-runtime-contract.json'),e=json('docs/operations/efficiency-operating-policy.json');
const t=r.images.binary_transport,i=e.image;
const operations=['create_blob','create_tree','create_commit','update_ref'];
function violations(a,b){const errors=[];if(a.method!=='github_git_data_api'||b.binary_transport!=='github_git_data_api')errors.push('primary_route');if(a.native_git_credentials_required!==false||b.native_git_credentials_required!==false)errors.push('native_credentials');if(a.local_file_host_token_is_connector_prerequisite!==false||b.local_file_host_token_is_connector_prerequisite!==false)errors.push('local_token_prerequisite');if(a.optional_helper_failure_blocks_connector!==false||b.optional_helper_failure_blocks_connector!==false)errors.push('helper_failure_scope');if(a.routing_policy_id!=='connector-first-v1'||b.routing_policy_id!=='connector-first-v1')errors.push('routing_identity');return errors;}
test('normal production and qualification retain the authenticated connector route',()=>{assert.deepEqual(violations(t,i),[]);assert.deepEqual(t.applies_to,['production','qualification_nonproduction']);assert.deepEqual(t.connector_tools,operations);assert.deepEqual(i.connector_git_data_tools,operations);});
test('no local credential or token export is introduced',()=>{assert.equal(t.connector_managed_authentication,true);assert.equal(i.connector_managed_authentication,true);assert.equal(t.credential_export_prohibited,true);assert.equal(i.credential_export_prohibited,true);});
test('Contents utility remains separate from the normal binary lane',()=>{assert.equal(t.github_contents_api_for_binary_images_prohibited,true);assert.equal(i.github_contents_api_for_png,false);assert.equal(t.contents_file_helper_scope,'independent_authenticated_host_utility_not_normal_image_lane');assert.equal(i.contents_file_helper_scope,t.contents_file_helper_scope);assert.equal(r.handoff.required_values.image_transport_method,'github_git_data_api');});
for(const [name,mutate] of [['primary route',a=>a.method='contents'],['local credentials',a=>a.native_git_credentials_required=true],['token prerequisite',a=>a.local_file_host_token_is_connector_prerequisite=true],['global helper blocker',a=>a.optional_helper_failure_blocks_connector=true],['routing identity',a=>a.routing_policy_id='different']])test('reject regression: '+name,()=>{const a=structuredClone(t);mutate(a);assert.ok(violations(a,i).length);});
test('efficiency policy cannot silently reintroduce the local-token gate',()=>{const b=structuredClone(i);b.local_file_host_token_is_connector_prerequisite=true;assert.ok(violations(t,b).includes('local_token_prerequisite'));});
test('recovery derives from live handoff state and preserves non-force writes',()=>{assert.ok(t.resume_commit_sequence.some(x=>x.includes('current isolated handoff branch')));assert.ok(t.resume_commit_sequence.some(x=>x.includes('observed handoff head')));assert.ok(t.resume_commit_sequence.some(x=>x.includes('Non-force')));});
for(const file of ['START-HERE.md','LIVING-SYSTEM-OPERATIONS.md','automated-image-execution.md','native-image-task-delivery.md','image-file-transfer.md'])test('current guidance matches machine policy: '+file,()=>{const text=fs.readFileSync('docs/operations/'+file,'utf8');const current=text.split('---')[0];assert.ok(current.includes('connector-first-v1'));assert.ok(current.includes('CAPABILITY_BLOCKED_CONNECTOR_BINARY_PAYLOAD_DELIVERY'));assert.ok(current.includes('A current denial stops that operation'));assert.ok(current.includes('all V2 raw/final provenance'));});
