import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {fileOperationStore,drainOperations,operationKey,OperationBlocked,hashBytes,operationView} from '../lib/durable-operation.mjs';
import {executeRecoverableImage,proveImageHandoff} from '../lib/recoverable-image-job.mjs';
import {connectorImageDelivery} from '../lib/connector-image-delivery.mjs';
import {editionBinding,executeEdition,canonicalExecutionStatus,pinnedResumeDecision,promotionDecision,sealPublicationBundle,verifyPublicationBundle,verifyAdmissionEvidence} from '../lib/edition-execution.mjs';
import {newRunState,checkpointRunStage} from '../lib/run-state.mjs';
import {buildImageGenerationExecution,executeImageRequest,validateImageExecutionReceipt} from '../lib/image-execution.mjs';
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'brief-reliable-'));
const usage=()=>({work_invocations:0,codex_invocations:0,paid_model_api_calls:0});
const sha='a'.repeat(40), now=()=> '2026-09-29T16:00:00Z';
const gitBlob=b=>createHash('sha1').update(Buffer.from('blob '+b.length+'\0')).update(b).digest('hex');
function crc32(b){let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function png(){const chunk=(type,body)=>{const b=Buffer.concat([Buffer.from(type),body]),n=Buffer.alloc(4),crc=Buffer.alloc(4);n.writeUInt32BE(body.length);crc.writeUInt32BE(crc32(b));return Buffer.concat([n,b,crc]);};const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(1200);ihdr.writeUInt32BE(630,4);ihdr[8]=8;ihdr[9]=6;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(Buffer.alloc((1200*4+1)*630))),chunk('IEND',Buffer.alloc(0))]);}
const packet=(id='m04')=>({story_id:'story-'+id,candidate_id:id,headline:'Supported single-story mechanism',source_url:'https://example.com/'+id,
  verified_visual_facts:['Verified source mechanism'],generic_conceptual_elements:['generic input','review checkpoint'],prohibited_specifics:['invented metrics'],
  visual_brief:'Detailed professional white-background 1200x630 editorial textbook illustration.',reference_policy:'Only source-supported specifics; generic explanatory concepts are explicitly conceptual.',
  acceptance_order:['subject','facts','structure','editorial'],wrong_subject_action:'Discard and generate a new request for this same story.',low_quality_fallback:false,
  allowed_image_text:['Input','Review'],composition_mode:'annotated_system',prohibited_composition_patterns:['generic sparse title card']});
function fixture(){
  const bytes=png(), stored=new Map(), outputs=new Map(), counts={generation:0,review:0,rawWrites:0,finalWrites:0};
  const host={id:'fixture-native-host',async generate(e,{key}){counts.generation++;const result={bytes:Buffer.from(bytes),executor:'native_chatgpt_image_generation',
    evidence_type:'fixture',call_id:'fixture-generation-'+key,artifact_id:'fixture-image-'+key,generated_at:'2026-09-29T15:00:00Z',owner_interventions:[],usage:usage()};outputs.set(key,result);return result;},
    async recover(key){return outputs.has(key)?{status:'complete',operation_key:key,invocation_id:'fixture-invocation-'+key,result:outputs.get(key)}:{status:'unknown'};},
    async review(b,e,{sha256}){counts.review++;return {mode:'automated',phase:'after_generation',call_id:'fixture-review',reviewed_at:'2026-09-29T15:30:00Z',
      asset_sha256:sha256,subject_match:'pass',factual_support:'pass',structural_quality:'pass',editorial_quality:'pass',usage:usage(),owner_interventions:[]};}};
  const transport={async ensure(p,b){if(stored.has(p)){assert.ok(stored.get(p).equals(b));}else{stored.set(p,Buffer.from(b));counts[p.startsWith('briefs/')?'finalWrites':'rawWrites']++;}return {path:p,commit_sha:sha,git_blob_sha:gitBlob(b),persisted_at:now(),owner_interventions:[]};},async read(p){return Buffer.from(stored.get(p));}};
  const admission={schema_version:'image-handoff-proof-v2',host_id:host.id,release_sha:sha,evidence_type:'fixture',
    verified_at:'2026-09-29T15:00:00Z',expires_at:'2026-09-29T17:00:00Z',raw_sha256:hashBytes(bytes),native_result_id:'fixture-probe',invocation_id:'fixture-task',git_readback_verified:true};
  return {host,transport,admission,counts,stored,outputs,bytes,store:fileOperationStore(temp()),executionMode:'qualification_nonproduction',
    editionId:'fixture-edition',editionDate:'2026-09-29',releaseSha:sha,evidenceType:'fixture',trigger:'fixture',now};
}

test('immutable journal CAS allows only one writer at a revision',async()=>{const s=fileOperationStore(temp()),k='1'.repeat(64);await s.cas(k,-1,{a:1});const results=await Promise.allSettled([s.cas(k,0,{a:2}),s.cas(k,0,{a:3})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await s.load(k)).version,1);});
test('atomic object storage preserves and verifies actual bytes',async()=>{const s=fileOperationStore(temp()),b=png(),r=await s.put(b);assert.ok((await s.read(r)).equals(b));assert.deepEqual(await s.put(b),r);await assert.rejects(s.read({...r,bytes:3}),/changed/);});
test('store rejects path injection and corrupted history',async()=>{const root=temp(),s=fileOperationStore(root);await assert.rejects(s.load('../escape'),/invalid/);const k='2'.repeat(64);await s.cas(k,-1,{a:1});fs.writeFileSync(path.join(root,k,'00000000.json'),'{"version":0,"previous_digest":"bad"}');await assert.rejects(s.load(k),/chain/);});
test('controller executes all ready dependencies without a follow-up prompt',async()=>{const s=fileOperationStore(temp()),calls=[];const r=await drainOperations({store:s,binding:{edition:'fixture'},now,steps:['first','second','third'].map(id=>({id,run:async()=>{calls.push(id);return {result:'pass'};}}))});assert.deepEqual(calls,['first','second','third']);assert.equal(r.status,'complete');assert.equal(r.next_operation,null);const r2=await drainOperations({store:s,binding:{edition:'fixture'},now,steps:['first','second','third'].map(id=>({id,run:async()=>{throw Error('must not run');}}))});assert.equal(r2.executed,0);});
test('completed effect and next action survive a crash after commit',async()=>{const s=fileOperationStore(temp()),calls=[],steps=['first','second'].map(id=>({id,run:async()=>{calls.push(id);return {id};}}));let crash=true;await assert.rejects(drainOperations({store:s,binding:{job:'crash'},steps,now,afterSave:async v=>{if(crash&&v.completed_operations.includes('first')){crash=false;throw Error('process lost');}}}),/process lost/);const r=await drainOperations({store:s,binding:{job:'crash'},steps,now});assert.deepEqual(calls,['first','second']);assert.equal(r.status,'complete');});
test('unknown side effect blocks and is not blindly retried on repeated status ticks',async()=>{const s=fileOperationStore(temp());let n=0;const steps=[{id:'send',run:async()=>{n++;throw Error('ack lost');}}],binding={job:'unknown'};await drainOperations({store:s,binding,steps,now});await drainOperations({store:s,binding,steps,now});assert.equal(n,1);const r=await drainOperations({store:s,binding,steps,now,signal:'investigated'});assert.equal(r.blocker,'OUTCOME_RECONCILIATION_REQUIRED');assert.equal(n,1);});
test('explicit recovery uses the original logical key without repeating the effect',async()=>{const store=fileOperationStore(temp());let key,starts=0;const steps=[{id:'effect',run:async c=>{key=c.key;starts++;throw Error('ack lost');},recover:async c=>{assert.equal(c.key,key);return {result:'pass',id:'observed-result'};}},{id:'next',run:async()=>({result:'pass'})}];const binding={job:'recover'};await drainOperations({store,binding,steps,now});const r=await drainOperations({store,binding,steps,now,signal:'response-found'});assert.equal(r.status,'complete');assert.equal(starts,1);});
test('unexpired lease prevents a second executor',async()=>{const store=fileOperationStore(temp()),binding={job:'lease'},key=operationKey(binding);await store.cas(key,-1,{binding,steps:['one'],cursor:0,status:'running',results:{},events:[],attempts:{},current:{id:'one',fence:1,lease:{owner:'other',expires_at:'2026-09-29T16:01:00Z'}}});let count=0;const r=await drainOperations({store,binding,now,steps:[{id:'one',run:async()=>{count++;return {};}}]});assert.equal(r.status,'running');assert.equal(count,0);});
test('same pinned job cannot quietly change its operation order',async()=>{const store=fileOperationStore(temp()),binding={job:'pin'};await drainOperations({store,binding,now,steps:[{id:'one',run:async()=>({})}]});await assert.rejects(drainOperations({store,binding,now,steps:[{id:'different',run:async()=>({})}]}),/pinned_execution_changed/);});
test('fixture operation cannot assert real public completion',async()=>{const r=await drainOperations({store:fileOperationStore(temp()),binding:{evidence_type:'fixture'},now,steps:[{id:'public_closed',run:async()=>({verified:true})}]});assert.equal(r.publication_complete,false);});

test('durable image job completes all phases with unchanged V2 validation',async()=>{const f=fixture(),e=buildImageGenerationExecution(packet()),r=await executeRecoverableImage(e,f);assert.equal(r.status,'fixture_pass');assert.deepEqual(validateImageExecutionReceipt(r,e,{allowFixture:true}),[]);assert.ok(validateImageExecutionReceipt(r,e).length);assert.deepEqual(f.counts,{generation:1,review:1,rawWrites:1,finalWrites:1});});
test('accepted durable image is reused without generation, review or upload',async()=>{const f=fixture(),e=buildImageGenerationExecution(packet());await executeRecoverableImage(e,f);const r=await executeRecoverableImage(e,f);assert.equal(r.reused,true);assert.deepEqual(f.counts,{generation:1,review:1,rawWrites:1,finalWrites:1});});
test('generation acknowledgement loss recovers real result before capture; no duplicate generation',async()=>{const f=fixture(),generate=f.host.generate;f.host.generate=async(...args)=>{await generate(...args);throw Error('generation ack lost');};const e=buildImageGenerationExecution(packet());let r=await executeRecoverableImage(e,f);assert.equal(r.accepted_locked,false);r=await executeRecoverableImage(e,{...f,signal:'native-response-now-visible'});assert.equal(r.status,'fixture_pass');assert.equal(f.counts.generation,1);});
test('final upload acknowledgement loss resumes persistence, not generation or review',async()=>{const f=fixture(),ensure=f.transport.ensure;let lose=true;f.transport.ensure=async(...args)=>{const r=await ensure(...args);if(args[0].startsWith('briefs/')&&lose){lose=false;throw Error('final ack lost');}return r;};const e=buildImageGenerationExecution(packet());await executeRecoverableImage(e,f);const r=await executeRecoverableImage(e,{...f,signal:'storage-reconciled'});assert.equal(r.status,'fixture_pass');assert.deepEqual(f.counts,{generation:1,review:1,rawWrites:1,finalWrites:1});});
test('crash after raw capture resumes remaining phases with original bytes',async()=>{const f=fixture(),e=buildImageGenerationExecution(packet());let once=true;await assert.rejects(executeRecoverableImage(e,{...f,afterSave:async v=>{if(once&&v.completed_operations.includes('capture')){once=false;throw Error('crash');}}}),/crash/);const r=await executeRecoverableImage(e,f);assert.equal(r.status,'fixture_pass');assert.deepEqual(f.counts,{generation:1,review:1,rawWrites:1,finalWrites:1});});
test('quality rejection preserves review and raw without final upload',async()=>{const f=fixture(),review=f.host.review;f.host.review=async(...a)=>({...await review(...a),subject_match:'fail'});const r=await executeRecoverableImage(buildImageGenerationExecution(packet()),f);assert.equal(r.quality_rejected,true);assert.equal(f.counts.finalWrites,0);assert.equal(r.state.results.review.subject_match,'fail');});
test('missing native recovery capability consumes zero image attempts',async()=>{const f=fixture();delete f.host.recover;const r=await executeRecoverableImage(buildImageGenerationExecution(packet()),f);assert.equal(r.attempts_allocated,0);assert.equal(f.counts.generation,0);});
test('new shared executor profile cannot silently fall back to volatile execution',async()=>{const r=await executeImageRequest(buildImageGenerationExecution(packet()),{executionProfile:'reliable-edition-v1'});assert.equal(r.status,'CAPABILITY_BLOCKED_DURABLE_STORE_REQUIRED');assert.equal(r.attempts_allocated,0);});
test('shared executor actually routes admitted jobs through durable phases',async()=>{const f=fixture(),r=await executeImageRequest(buildImageGenerationExecution(packet()),{...f,operationStore:f.store,executionProfile:'reliable-edition-v1'});assert.equal(r.status,'fixture_pass');assert.equal(f.counts.generation,1);});
test('expired admission does not trigger a fresh generation',async()=>{const f=fixture();f.admission.expires_at='2026-09-29T15:59:00Z';const r=await executeRecoverableImage(buildImageGenerationExecution(packet()),f);assert.equal(r.blocker,'HOST_ADMISSION_EXPIRED');assert.equal(f.counts.generation,0);});
test('paid provenance is blocked without reviewer or storage calls',async()=>{const f=fixture(),g=f.host.generate;f.host.generate=async(...a)=>({...await g(...a),usage:{...usage(),paid_model_api_calls:1}});const r=await executeRecoverableImage(buildImageGenerationExecution(packet()),f);assert.equal(r.accepted_locked,false);assert.equal(f.counts.rawWrites,0);assert.equal(f.counts.review,0);});
test('image handoff proof requires actual recovery, matching identity and exact remote bytes',async()=>{const f=fixture(),key='6'.repeat(64),g=await f.host.generate(buildImageGenerationExecution(packet()),{key});const p=await proveImageHandoff({host:f.host,transport:f.transport,probeKey:key,expected:{native_result_id:g.call_id,artifact_id:g.artifact_id,sha256:hashBytes(g.bytes)},releaseSha:sha,now});assert.equal(p.evidence_type,'fixture');assert.equal(p.git_readback_verified,true);assert.equal(f.counts.generation,1);});
test('handoff proof rejects a task/result mismatch and mismatched raw bytes',async()=>{const f=fixture(),key='7'.repeat(64),g=await f.host.generate(buildImageGenerationExecution(packet()),{key});const args={host:f.host,transport:f.transport,probeKey:key,expected:{native_result_id:g.call_id,artifact_id:g.artifact_id,sha256:'0'.repeat(64)},releaseSha:sha,now};await assert.rejects(proveImageHandoff(args),/mismatch/);});

const binding=()=>editionBinding({editionId:'dab-edition-2026-09-29',date:'2026-09-29',cutoff:'2026-09-29T14:00:00Z',releaseSha:sha,researchBaselineSha:sha,policies:{article:'article-24-72-168-v1'},executionId:'execution-1'});
test('edition admission precedes every costly stage when the real host is missing',async()=>{let calls=0;const r=await executeEdition({binding:binding(),store:fileOperationStore(temp()),now,handlers:{discovery:{run:async()=>{calls++;return {result:'pass'};}}}});assert.equal(calls,0);assert.equal(r.blocker,'CAPABILITY_BLOCKED_NATIVE_RESULT_HANDOFF');assert.equal(r.next_operation,'admission');});
test('fixture handoff cannot admit a live edition',async()=>{const f=fixture(),key='8'.repeat(64),g=await f.host.generate(buildImageGenerationExecution(packet()),{key});let calls=0;const r=await executeEdition({binding:binding(),store:fileOperationStore(temp()),host:f.host,transport:f.transport,probeKey:key,expectedProbe:{native_result_id:g.call_id,artifact_id:g.artifact_id,sha256:hashBytes(g.bytes)},now,handlers:{discovery:{run:async()=>{calls++;return {result:'pass'};}}}});assert.equal(r.blocker,'fixture_cannot_admit_live_edition');assert.equal(calls,0);});
test('a failed qualification result cannot be reopened by continuation',async()=>{const r=await executeEdition({binding:binding(),store:fileOperationStore(temp()),terminalResult:{result:'fail',run_id:'2026-09-29-Q25'}});assert.equal(r.resume_permitted,false);assert.equal(r.result,'fail');});
test('terminal result wins over stale nonterminal narrative',()=>{const r=canonicalExecutionStatus({terminalResult:{result:'fail',run_id:'Q25'},checkpointText:'Q25 is nonterminal.'});assert.equal(r.status,'terminal_fail');assert.equal(r.narrative_conflict,true);assert.equal(r.publication_complete,false);});
test('promotion preserves a bundle but requires explicit compatibility when main changes',()=>{const bundle={release_sha:sha,bundle_sha256:'b'.repeat(64)};const r=promotionDecision(bundle,{targetReleaseSha:'c'.repeat(40),productionIdentity:'editorial-handoff/production/2026-09-29',qualification:{result:'pass',execution_mode:'qualification_nonproduction',bundle_sha256:bundle.bundle_sha256}});assert.equal(r.action,'COMPATIBILITY_MIGRATION_REQUIRED');assert.equal(r.restart_editorial,false);});
test('failed or unbound qualification cannot be promoted',()=>{const r=promotionDecision({release_sha:sha,bundle_sha256:'b'.repeat(64)},{targetReleaseSha:sha,productionIdentity:'editorial-handoff/production/2026-09-29',qualification:{result:'fail'}});assert.equal(r.action,'BLOCK');});
test('promotion does not regenerate images or equate a pass to public closure',()=>{const b={release_sha:sha,bundle_sha256:'b'.repeat(64)};const r=promotionDecision(b,{targetReleaseSha:sha,productionIdentity:'editorial-handoff/production/2026-09-29',qualification:{result:'pass',execution_mode:'qualification_nonproduction',bundle_sha256:b.bundle_sha256}});assert.equal(r.action,'PROMOTE_VERIFIED_BUNDLE');assert.equal(r.regenerate_images,false);assert.equal(r.public_closed,false);});
test('pinned resume does not discard valid research after a main-only change',()=>{const root=temp();fs.writeFileSync(path.join(root,'evidence.json'),'{}');let state=newRunState({date:'2026-09-29',baselineSha:sha});state=checkpointRunStage(root,state,'PREFLIGHT_METADATA_READY',{artifactPaths:['evidence.json']});const r=pinnedResumeDecision(root,state,'b'.repeat(40));assert.equal(r.resume_stage,'PREFLIGHT_DISCOVERY_READY');assert.equal(r.deployment_rebinding_required,true);assert.equal(r.restart_editorial_due_to_main_change,false);assert.deepEqual(r.preserved_stages,['PREFLIGHT_METADATA_READY']);});
test('bundle sealing refuses an incomplete manifest rather than fabricate publication readiness',()=>{const root=temp();fs.writeFileSync(path.join(root,'manifest.json'),'{}');assert.throws(()=>sealPublicationBundle(root,'manifest.json',{releaseSha:sha,cutoff:now()}),/bundle_not_publishable/);});
test('bundle verifier detects a tampered bundle identity',()=>{assert.throws(()=>verifyPublicationBundle(temp(),{schema_version:'sealed-edition-bundle-v1',bundle_sha256:'0'.repeat(64),artifacts:[]}),/identity_changed/);});

// Integration contract against a real LOCAL Git object database. This exercises
// executable binary transport; it is NOT evidence of a live ChatGPT connector bridge.
import {execFileSync} from 'node:child_process';
function localGitConnector(){
  const root=temp(),branch='editorial-handoff/qualification/fixture',counts={blobs:0,updates:0};
  const git=(args,input=null,extra={})=>execFileSync('git',args,{cwd:root,input,maxBuffer:16*1024*1024,env:{...process.env,GIT_AUTHOR_NAME:'Fixture',GIT_AUTHOR_EMAIL:'fixture@example.invalid',GIT_COMMITTER_NAME:'Fixture',GIT_COMMITTER_EMAIL:'fixture@example.invalid',...extra},stdio:['pipe','pipe','pipe']});
  git(['init','-q']);fs.writeFileSync(path.join(root,'preserved.txt'),'keep exact bytes');git(['add','.']);git(['commit','-qm','fixture baseline']);git(['branch',branch]);
  const api={
    async fetch({url}){const u=new URL(url),p=u.pathname.split('/repos/fixture/repo/')[1];
      if(p.startsWith('git/ref/heads/'))return {object:{sha:git(['rev-parse',p.slice('git/ref/heads/'.length)]).toString().trim()}};
      if(p.startsWith('git/commits/'))return {tree:{sha:git(['rev-parse',p.slice('git/commits/'.length)+'^{tree}']).toString().trim()}};
      if(p.startsWith('git/trees/'))return {truncated:false,tree:git(['ls-tree','-z',p.slice('git/trees/'.length)]).toString().split('\0').filter(Boolean).map(line=>{const m=line.match(/^(\d+) (\w+) ([a-f0-9]+)\t(.+)$/s);return {mode:m[1],type:m[2],sha:m[3],path:m[4]};})};
      throw Error('unexpected API '+p);
    },
    async create_blob({content,encoding}){counts.blobs++;assert.equal(encoding,'base64');return {result:{sha:git(['hash-object','-w','--stdin'],Buffer.from(content,'base64')).toString().trim()}};},
    async create_tree({base_tree_sha,tree_elements}){const env={GIT_INDEX_FILE:path.join(root,'fixture-index')};git(['read-tree',base_tree_sha],null,env);for(const e of tree_elements)git(['update-index','--add','--cacheinfo',e.mode,e.sha,e.path],null,env);return {result:{sha:git(['write-tree'],null,env).toString().trim()}};},
    async create_commit({tree_sha,parent_sha,message}){return {result:{sha:git(['commit-tree',tree_sha,'-p',parent_sha],message+'\n').toString().trim()}};},
    async update_ref({branch_name,sha:next,force}){assert.equal(force,false);const old=git(['rev-parse',branch_name]).toString().trim();git(['merge-base','--is-ancestor',old,next]);git(['update-ref','refs/heads/'+branch_name,next,old]);counts.updates++;return {result:{success:true}};}
  };
  const readBytes=async({path:p,commit})=>git(['show',commit+':'+p]);
  return {root,git,api,branch,counts,readBytes,transport:connectorImageDelivery({api,repository:'fixture/repo',branch,readBytes,now})};
}
test('canonical connector implementation transfers complete >1 MiB binary bytes to real Git',async()=>{const f=localGitConnector(),bytes=Buffer.concat([png(),Buffer.alloc(1200000,137)]),p='_records/image-attempts/fixture/m04/attempt-1/raw.png';const r=await f.transport.ensure(p,bytes,{key:'9'.repeat(64)});assert.ok((await f.transport.read(p,r.commit_sha)).equals(bytes));assert.equal(r.git_blob_sha,gitBlob(bytes));assert.equal(f.git(['show',r.commit_sha+':preserved.txt']).toString(),'keep exact bytes');assert.deepEqual(f.counts,{blobs:1,updates:1});});
test('identical connector upload reuses committed exact bytes without another write',async()=>{const f=localGitConnector(),p='briefs/images/2026-09-29/test.png',b=png();await f.transport.ensure(p,b,{key:'9'.repeat(64)});const r=await f.transport.ensure(p,b,{key:'9'.repeat(64)});assert.equal(r.reused,true);assert.deepEqual(f.counts,{blobs:1,updates:1});});
test('connector refuses silent replacement of different bytes',async()=>{const f=localGitConnector(),p='briefs/images/2026-09-29/test.png';await f.transport.ensure(p,png(),{key:'9'.repeat(64)});await assert.rejects(f.transport.ensure(p,Buffer.from('other'),{key:'9'.repeat(64)}),/immutable_image_conflict/);assert.equal(f.counts.updates,1);});
test('unknown connector update acknowledgement recovers by reading the committed path',async()=>{const f=localGitConnector(),update=f.api.update_ref;let lose=true;f.api.update_ref=async a=>{const r=await update(a);if(lose){lose=false;throw Error('connection lost after update');}return r;};const p='briefs/images/2026-09-29/test.png',b=png();await assert.rejects(f.transport.ensure(p,b,{key:'a'.repeat(64)}),/connection lost/);const r=await f.transport.ensure(p,b,{key:'a'.repeat(64)});assert.equal(r.reused,true);assert.deepEqual(f.counts,{blobs:1,updates:1});});
test('connector denial stops the operation, without fallback transport or branch update',async()=>{const f=localGitConnector();f.api.create_blob=async()=>({error:'denied',error_http_status_code:403});await assert.rejects(f.transport.ensure('briefs/images/2026-09-29/test.png',png(),{key:'b'.repeat(64)}),/FAILED_OR_DENIED/);assert.equal(f.counts.updates,0);});
test('connector requires a binary reader and refuses main or unsafe paths',async()=>{const f=localGitConnector();assert.throws(()=>connectorImageDelivery({api:f.api,repository:'fixture/repo',branch:'main',readBytes:f.readBytes}),/isolated/);assert.throws(()=>connectorImageDelivery({api:f.api,repository:'fixture/repo',branch:f.branch}),/binary_reader/);await assert.rejects(f.transport.ensure('../main.png',png(),{key:'a'.repeat(64)}),/real_image/);});
test('incomplete Base64 delivery is caught by the returned Git blob identity',async()=>{const f=localGitConnector(),create=f.api.create_blob;f.api.create_blob=async a=>create({...a,content:a.content.slice(0,20)});await assert.rejects(f.transport.ensure('briefs/images/2026-09-29/test.png',png(),{key:'c'.repeat(64)}),/payload_mismatch/);assert.equal(f.counts.updates,0);});
test('a text-only readback cannot be accepted as binary persistence',async()=>{const f=localGitConnector(),t=connectorImageDelivery({api:f.api,repository:'fixture/repo',branch:f.branch,readBytes:async()=>'/mnt/data/fake-path.png',now});await assert.rejects(t.ensure('briefs/images/2026-09-29/test.png',png(),{key:'d'.repeat(64)}),/exact_bytes/);});

// Capability refresh is not a new request identity or permission to regenerate.
test('a refreshed admission proof reuses the identical completed image job',async()=>{const f=fixture(),e=buildImageGenerationExecution(packet());const first=await executeRecoverableImage(e,f);f.admission={...f.admission,verified_at:'2026-09-29T15:59:00Z',expires_at:'2026-09-29T17:30:00Z'};const second=await executeRecoverableImage(e,f);assert.equal(second.job_key,first.job_key);assert.equal(second.reused,true);assert.equal(f.counts.generation,1);});
test('expired pre-generation admission consumes no attempt and leaves no generation intent',async()=>{const f=fixture(),e=buildImageGenerationExecution(packet());f.admission.expires_at='2026-09-29T15:59:00Z';const r=await executeRecoverableImage(e,f);assert.equal(r.status,'HOST_ADMISSION_EXPIRED');assert.equal(r.attempts_allocated,0);assert.equal(f.counts.generation,0);f.admission.expires_at='2026-09-29T17:00:00Z';const done=await executeRecoverableImage(e,f);assert.equal(done.status,'fixture_pass');assert.equal(f.counts.generation,1);});
test('offline admission requires real recovered bytes, not true capability flags',()=>{const root=temp(),key='e'.repeat(64),bytes=png(),p=path.join(root,'_records/image-attempts/handoff-proof',key,'raw.png');fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,bytes);const proof={schema_version:'image-handoff-proof-v2',host_id:'declared-test-host',invocation_id:'test-invocation',native_result_id:'test-result',artifact_id:'test-artifact',release_sha:sha,evidence_type:'live',operation_key:key,git_readback_verified:true,git_commit_sha:sha,raw_sha256:hashBytes(bytes),git_blob_sha:gitBlob(bytes),verified_at:'2026-09-29T15:00:00Z',expires_at:'2026-09-29T17:00:00Z'};assert.equal(verifyAdmissionEvidence(root,proof,{releaseSha:sha,now:now()}).result,'pass');assert.throws(()=>verifyAdmissionEvidence(root,{...proof,raw_sha256:'0'.repeat(64)},{releaseSha:sha,now:now()}),/MISMATCH/);assert.throws(()=>verifyAdmissionEvidence(root,{...proof,evidence_type:'fixture'},{releaseSha:sha,now:now()}),/CAPABILITY_BLOCKED/);assert.throws(()=>verifyAdmissionEvidence(root,proof,{releaseSha:'f'.repeat(40),now:now()}),/CAPABILITY_BLOCKED/);assert.throws(()=>verifyAdmissionEvidence(root,proof,{releaseSha:sha,now:'2026-09-29T18:00:00Z'}),/EXPIRED/);});
